---

- name: Ensure that gpg is installed
  become: True
  package:
    name: gpg
    state: present

- name: Add Docker apt key
  become: True
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker apt repo
  become: True
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker
  become: True
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
